### PR TITLE
Fix mypy version allowance

### PR DESCRIPTION
**Pull request by enrico-ghidoni**

### CODE REVIEW

**Review by lastmikoi — CHANGES_REQUESTED** [review]
`mypy>=0.570,<1`
`pytest-mypy>=0.3.1,<1`

I explicitly put the `<0.570` because of a breaking change that broke pytest-mypy.

Only pytest-mypy 0.3.1 and higher support mypy 0.570 and higher.

**Comment by enrico-ghidoni** [comment]
`mypy<0.570` is not supported by `pytest-mypy<0.3.1` (see #4)

**Comment by lastmikoi** [comment]
You've just repeated what I wrote... Sleep deprivation much ? :)

**Comment by enrico-ghidoni** [comment]
If you get `pytest-mypy==0.3.0` and `mypy==0.560` it won't work

**Comment by lastmikoi** [comment]
Which is why we explicitly depend on:
```
mypy>=0.570,<1
pytest-mypy>=0.3.1,<1
```
which **explicitly** excludes the case of `pytest-mypy==0.3.0` and `mypy==0.560`.

**Comment by enrico-ghidoni** [comment]
Next time write "change `pytest-mypy>=0.3,<1` to `pytest-mypy>=0.3.1,<1`"

**Comment by lastmikoi** [comment]
And mypy from 0.521 to 0.570.

**Review by lastmikoi — APPROVED** [review]

**Pull request merged**
